module.exports = [
  {
    "id": 1,
    "regId": "CODIENYCH-2026-0001",
    "teamId": "CODIENYCH-2026-0001",
    "teamName": "Technical coders",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Mahalakshmi s",
    "email": "mahalakshmisundar73@gmail.com",
    "phone": "8940451678",
    "college": "Shree Venkateshwara Hi-tech engineering college",
    "members": "Mayukasri s, Deepaka p, Indhumathi m",
    "utr": "130061965577",
    "isAdmin": false
  },
  {
    "id": 2,
    "regId": "CODIENYCH-2026-0002",
    "teamId": "CODIENYCH-2026-0002",
    "teamName": "CRUST INNOVATORS",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "devanand . S",
    "email": "devanand.s2008@gmail.com",
    "phone": "6369629723",
    "college": "avs engineering college , salem",
    "members": "nandhini . s, karthiga . s, dharsana k",
    "utr": "626676234759",
    "isAdmin": false
  },
  {
    "id": 3,
    "regId": "CODIENYCH-2026-0003",
    "teamId": "CODIENYCH-2026-0003",
    "teamName": "Hack Rat",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Saran s",
    "email": "harisaran0527@gmail.com",
    "phone": "8610633056",
    "college": "avs engineering college",
    "members": "nivetha e, karthika p, Kavin e",
    "utr": "626658236508",
    "isAdmin": false
  },
  {
    "id": 4,
    "regId": "CODIENYCH-2026-0004",
    "teamId": "CODIENYCH-2026-0004",
    "teamName": "NEXORA",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Narmatha R",
    "email": "narmathar1412@gmail.com",
    "phone": "+919361716591",
    "college": "K. RAMAKRISHNAN COLLEGE OF ENGINEERING",
    "members": "Nifra Fathima M, Swathika K, Harinisri t, Lerthika n, Susindaran r",
    "utr": "130102152843",
    "isAdmin": false
  },
  {
    "id": 5,
    "regId": "CODIENYCH-2026-0005",
    "teamId": "CODIENYCH-2026-0005",
    "teamName": "Game of codes",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 5,
    "leader": "Abirama Sunthari A",
    "email": "abiramasunthari67@gmail.com",
    "phone": "9003945468",
    "college": "K Ramakrishnan College of Engineering",
    "members": "Riyaas m, Aravind m, Hyder ali khan j, Tamil alagan m",
    "utr": "130091385920",
    "isAdmin": false
  },
  {
    "id": 6,
    "regId": "CODIENYCH-2026-0006",
    "teamId": "CODIENYCH-2026-0006",
    "teamName": "Code crafters",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Gayathri v",
    "email": "gayathriviswanathan2k@gmail.com",
    "phone": "8072263991",
    "college": "Shree Venkateshwara hi TECH engineering college",
    "members": "Gayathri g, Jesima z, Monisha s",
    "utr": "62679954025",
    "isAdmin": false
  },
  {
    "id": 7,
    "regId": "CODIENYCH-2026-0007",
    "teamId": "CODIENYCH-2026-0007",
    "teamName": "Mind flayers",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Mubeena S",
    "email": "24uea033@avinuty.ac.in",
    "phone": "8248361185",
    "college": "Avinashilingam institute for home science and higher education for women",
    "members": "Rihan jaith s, Jumana Haseen a m, Shameena s p, Pradhiksha R, Dharshini s",
    "utr": "663391812476",
    "isAdmin": false
  },
  {
    "id": 8,
    "regId": "CODIENYCH-2026-0008",
    "teamId": "CODIENYCH-2026-0008",
    "teamName": "CAPSLOCK",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "Kishore V",
    "email": "kishorevel25032007@gmail.com",
    "phone": "+918072610972",
    "college": "IFET COLLEGE OF ENGINEERING",
    "members": "JEEVIKA.SS, KIRUTHIGA.V, KAVINILA.V, MANISH.A, HEMACHANDRAN.B",
    "utr": "130234865689",
    "isAdmin": false
  },
  {
    "id": 9,
    "regId": "CODIENYCH-2026-0009",
    "teamId": "CODIENYCH-2026-0009",
    "teamName": "NexTerra",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Shri dharshini s",
    "email": "24ucs144@kamarajengg.edu.in",
    "phone": "9994309788",
    "college": "Kamaraj college of engineering and technology",
    "members": "Yuvan karthikeyan a, AnbuSelvan s, Sri Gayathri s, Sujitha t, Sureka r",
    "utr": "626990452983",
    "isAdmin": false
  },
  {
    "id": 10,
    "regId": "CODIENYCH-2026-0010",
    "teamId": "CODIENYCH-2026-0010",
    "teamName": "TRAILBLAZERS",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "VIJAYABASKAR B",
    "email": "vijayabaskarb.24eee@kongu.edu",
    "phone": "+919578782464",
    "college": "KONGU ENGINEERING COLLEGE",
    "members": "NIVEDHA VENKATESH, SANCHITHA S",
    "utr": "nivedhavenkatesh31-1@okaxis",
    "isAdmin": false
  },
  {
    "id": 11,
    "regId": "CODIENYCH-2026-0011",
    "teamId": "CODIENYCH-2026-0011",
    "teamName": "SADLIX",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 4,
    "leader": "SUBBIAH DAS I",
    "email": "dasvasanth93@gmail.com",
    "phone": "+91 8610026534",
    "college": "Annai vailankani college of engineering",
    "members": "SABAREESH E, SHAJIN X, LINGESH M S",
    "utr": "663544325944",
    "isAdmin": false
  },
  {
    "id": 12,
    "regId": "CODIENYCH-2026-0012",
    "teamId": "CODIENYCH-2026-0012",
    "teamName": "Code_pirates",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Surendhar s",
    "email": "surendharsesha@gmail.com",
    "phone": "+917010952084",
    "college": "Ifet college of engineering",
    "members": "Shrihari k, Prabavathy k, Rufaitha r",
    "utr": "663624222896",
    "isAdmin": false
  },
  {
    "id": 13,
    "regId": "CODIENYCH-2026-0013",
    "teamId": "CODIENYCH-2026-0013",
    "teamName": "NEURAL_TIDE",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 5,
    "leader": "Nafeeza Z",
    "email": "znafeeza8603@gmail.com",
    "phone": "+916384881696",
    "college": "ifet College of engineering",
    "members": "Joselin Margrate Blesse S E, R .Prashanthi, S.PREMKUMAR, M. NEERAJ",
    "utr": "627067820744",
    "isAdmin": false
  },
  {
    "id": 14,
    "regId": "CODIENYCH-2026-0014",
    "teamId": "CODIENYCH-2026-0014",
    "teamName": "Tech Titans",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Sri Nithii V S",
    "email": "srinithii2007@gmail.com",
    "phone": "7604858131",
    "college": "Annamalai University",
    "members": "Varshitha M, Chandru M, Gnanakrishnan P",
    "utr": "T2609271913319112206149",
    "isAdmin": false
  },
  {
    "id": 15,
    "regId": "CODIENYCH-2026-0015",
    "teamId": "CODIENYCH-2026-0015",
    "teamName": "Winvexa",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Rooney sharon r",
    "email": "24uea053@avinuty.ac.in",
    "phone": "8903274056",
    "college": "Avinashilingam institute for home science and higher education for women",
    "members": "Nivetha n, Luxsruthi l, Harshavarthini m, Prithika s, Ruthra priya p",
    "utr": "663621389294",
    "isAdmin": false
  },
  {
    "id": 16,
    "regId": "CODIENYCH-2026-0016",
    "teamId": "CODIENYCH-2026-0016",
    "teamName": "TECH TITANS",
    "originalTrack": "Cyber Security",
    "domain": "Cybersecurity & Privacy",
    "size": 6,
    "leader": "ARUL KUMARAN T",
    "email": "arulkumarant18@gmail.com",
    "phone": "6383400671",
    "college": "M. Kumarasamy college OF ENGINEERING",
    "members": "GUKAN G, dharshikhAN V R, KAVIN M, DEVINDREN M, MIDHUN V",
    "utr": "627113449638",
    "isAdmin": false
  },
  {
    "id": 17,
    "regId": "CODIENYCH-2026-0017",
    "teamId": "CODIENYCH-2026-0017",
    "teamName": "Techie three",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "Sudharsan B",
    "email": "sudharsai24@gmail.com",
    "phone": "+919095884379",
    "college": "Nandha Engineering college",
    "members": "Sudarsan b, Thanigai velan g",
    "utr": "627112634309",
    "isAdmin": false
  },
  {
    "id": 18,
    "regId": "CODIENYCH-2026-0018",
    "teamId": "CODIENYCH-2026-0018",
    "teamName": "INNOVENTURES",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "Sanjitha E",
    "email": "sanjitha102206@gmail.com",
    "phone": "9047980462",
    "college": "KPR Institute of Engineering and Technology",
    "members": "SHRIDHANYA G, bairavi s, priyadharshan s, GOkulnanthan c, KOwshik v",
    "utr": "663707668093",
    "isAdmin": false
  },
  {
    "id": 19,
    "regId": "CODIENYCH-2026-0019",
    "teamId": "CODIENYCH-2026-0019",
    "teamName": "VOID_CREW",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 5,
    "leader": "Prakash",
    "email": "prakashponnusamyt@gmail.com",
    "phone": "+919750415312",
    "college": "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "members": "DHARSHNA KUMAR K S, SIVARANJAN C, SARAN M, MOHAMED SHAHEEM S",
    "utr": "627134582246",
    "isAdmin": false
  },
  {
    "id": 20,
    "regId": "CODIENYCH-2026-0020",
    "teamId": "CODIENYCH-2026-0020",
    "teamName": "ALGO BRIGADE",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "YUVARAJ S",
    "email": "yuvarajs9606@gmail.com",
    "phone": "6379881238",
    "college": "PSNA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "members": "VAITHESVARANARAYAN M D, VELMURUGAN T, VIGASHINI K, VANIKRISHNA V, VARSHNI S",
    "utr": "627158713963",
    "isAdmin": false
  },
  {
    "id": 21,
    "regId": "CODIENYCH-2026-0021",
    "teamId": "CODIENYCH-2026-0021",
    "teamName": "Technova",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Kanimozhi S",
    "email": "kanisatha2008@gmail.com",
    "phone": "6374802663",
    "college": "Rathinam Technical Campus",
    "members": "Chinthana S, Monish p, Dharshini M, Fathima Hassna N, Akshay Jino K G",
    "utr": "627119410834",
    "isAdmin": false
  },
  {
    "id": 22,
    "regId": "CODIENYCH-2026-0022",
    "teamId": "CODIENYCH-2026-0022",
    "teamName": "Access Denied",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Sangeeth Krishna AM",
    "email": "sangeethkrishna0726@gmail.com",
    "phone": "+91 98471 52604",
    "college": "Excel Engineering College",
    "members": "Varun Krishna P, Thangjam Delin meitei, Sahar tn",
    "utr": "627196501975",
    "isAdmin": false
  },
  {
    "id": 23,
    "regId": "CODIENYCH-2026-0023",
    "teamId": "CODIENYCH-2026-0023",
    "teamName": "AXIOM",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "MUKIL BARATH S S",
    "email": "mukilbarathss@gmail.com",
    "phone": "9994739537",
    "college": "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "members": "LIHASH L B, SALINI N, LAKSHANA S, MOHAMMED SUHAIL A R, ROSHAN R",
    "utr": "627273996759",
    "isAdmin": false
  },
  {
    "id": 24,
    "regId": "CODIENYCH-2026-0024",
    "teamId": "CODIENYCH-2026-0024",
    "teamName": "CodeX",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "HEAMANTH K R S",
    "email": "heamanthkrs8@gmail.com",
    "phone": "8695786958",
    "college": "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "members": "FAYZUL WAHIT A, KANISHKA S, MAHALAKSHMI R",
    "utr": "614978758388",
    "isAdmin": false
  },
  {
    "id": 25,
    "regId": "CODIENYCH-2026-0025",
    "teamId": "CODIENYCH-2026-0025",
    "teamName": "IOT INNOVATORS",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 6,
    "leader": "Lalith kumar.a",
    "email": "kumarlalith891@gmail.com",
    "phone": "9025991039",
    "college": "Nandha engineering college",
    "members": "Aakash.n, Anish.a, Bharanidharan.s, Ethigash.k.p, Abbhishek.k.a",
    "utr": "9894490247@kotakbank",
    "isAdmin": false
  },
  {
    "id": 26,
    "regId": "CODIENYCH-2026-0026",
    "teamId": "CODIENYCH-2026-0026",
    "teamName": "CYBERSPARKZ",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "THANGARAJ S",
    "email": "ssdharan304@gmail.com",
    "phone": "9790390337",
    "college": "AVS ENGINEERING COLLEGE",
    "members": "anupriyan j n, sri hari kumaran b, THENNARASAN V",
    "utr": "734193373843",
    "isAdmin": false
  },
  {
    "id": 27,
    "regId": "CODIENYCH-2026-0027",
    "teamId": "CODIENYCH-2026-0027",
    "teamName": "NEXORA",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "tHANNUSHIYA.t",
    "email": "thannushiyathangavel@gmail.com",
    "phone": "8122967393",
    "college": "velalar college of engineering and technology , thindal ,erode",
    "members": "sabithashree.s, rubiga.d, reshma.r, p.devadharshini, rohita.s",
    "utr": "sabithashreebk-2@okaxis",
    "isAdmin": false
  },
  {
    "id": 28,
    "regId": "CODIENYCH-2026-0028",
    "teamId": "CODIENYCH-2026-0028",
    "teamName": "Sensors Squad",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 6,
    "leader": "LUVIS S",
    "email": "luviscr43@gmail.com",
    "phone": "6369030633",
    "college": "Nandha engineering college",
    "members": "Harish k, Kiruthik ragul m, Karthik m, Kavin raj A, Hariharasudan K K",
    "utr": "093629809753",
    "isAdmin": false
  },
  {
    "id": 29,
    "regId": "CODIENYCH-2026-0029",
    "teamId": "CODIENYCH-2026-0029",
    "teamName": "ZENITH VERSE",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "SURYA . K",
    "email": "suryaavs.work@gmail.com",
    "phone": "9150629649",
    "college": "AVS ENGINEERING COLLEGE",
    "members": "HASSAN RAJ . R, DEVIKA . P, SAI KEERTI . N.M, SUSMITHA. B, JAGADEEP . M",
    "utr": "663939455325",
    "isAdmin": false
  },
  {
    "id": 30,
    "regId": "CODIENYCH-2026-0030",
    "teamId": "CODIENYCH-2026-0030",
    "teamName": "Apex_go",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "DEEPAK KUMAR. D",
    "email": "vigneshdeepak222@gmail.com",
    "phone": "+917871538005",
    "college": "VELLORE INSTITUTE of technology",
    "members": "Sabarishwaran j, Sanjay s, Kowshik, sudharsan r",
    "utr": "664025789602",
    "isAdmin": false
  },
  {
    "id": 31,
    "regId": "CODIENYCH-2026-0031",
    "teamId": "CODIENYCH-2026-0031",
    "teamName": "Team wandal",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "Nithish s",
    "email": "nithish.2023a@vitstudent.ac.in",
    "phone": "7845909645",
    "college": "Vellore Institute Of Technology",
    "members": "Saravanakumar B, Nithish A, Pachaiyappan C, Aakshay s, Mugilan R",
    "utr": "578232582746",
    "isAdmin": false
  },
  {
    "id": 32,
    "regId": "CODIENYCH-2026-0032",
    "teamId": "CODIENYCH-2026-0032",
    "teamName": "TRAVART",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "SANJAY S",
    "email": "sanjaysundravadivel06@gmail.com",
    "phone": "7708411317",
    "college": "dr ngp institute of technology",
    "members": "s anitha, varsha p, swathi n",
    "utr": "627411831506",
    "isAdmin": false
  },
  {
    "id": 33,
    "regId": "CODIENYCH-2026-0033",
    "teamId": "CODIENYCH-2026-0033",
    "teamName": "Tech Innovators",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Deepika P",
    "email": "deepikakanga1512@gmail.com",
    "phone": "+91 70109 57839",
    "college": "KSR college of engineering",
    "members": "Naveena S, Kaviya E, Kiruthika Anbarasu, Kavya Shree P, Nagammai B",
    "utr": "127640719385",
    "isAdmin": false
  },
  {
    "id": 34,
    "regId": "CODIENYCH-2026-0034",
    "teamId": "CODIENYCH-2026-0034",
    "teamName": "WINFORGE",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "SRI BALAJI K R",
    "email": "bsri65959@gmail.com",
    "phone": "9150005776",
    "college": "DR N.G.P INSITUTE OF TECHNOLOGY",
    "members": "SRIDHAR JEYARAM ,B, r .ANTO REX, MIRUDUL VIKASH v, SELVAM S, SUDHEESH KRISHNA S M",
    "utr": "664055314260",
    "isAdmin": false
  },
  {
    "id": 35,
    "regId": "CODIENYCH-2026-0035",
    "teamId": "CODIENYCH-2026-0035",
    "teamName": "Nexora",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Nivarithika M",
    "email": "nivarithika@gmail.com",
    "phone": "7604950610",
    "college": "K. S. Rangasamy College of Technology",
    "members": "Ashmita s a, Hajira Banu H, HARINI A",
    "utr": "627420596800",
    "isAdmin": false
  },
  {
    "id": 36,
    "regId": "CODIENYCH-2026-0036",
    "teamId": "CODIENYCH-2026-0036",
    "teamName": "tech crew",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "hari prasath",
    "email": "hariprasath.nova@gmail.com",
    "phone": "8248473791",
    "college": "ifet college of engineering",
    "members": "deva, abirami, bharathi",
    "utr": "sundarcar400-1@oksbi",
    "isAdmin": false
  },
  {
    "id": 37,
    "regId": "CODIENYCH-2026-0037",
    "teamId": "CODIENYCH-2026-0037",
    "teamName": "Team nova",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "Sudhir.g",
    "email": "sudhirgopi68@gmail.com",
    "phone": "9345291393",
    "college": "Nandha engineering college",
    "members": "Rajtamil.s, Santhosh.s, Tamilselvan.s, Yuvashri.s, Keerthana.b",
    "utr": "664255146390",
    "isAdmin": false
  },
  {
    "id": 38,
    "regId": "CODIENYCH-2026-0038",
    "teamId": "CODIENYCH-2026-0038",
    "teamName": "PRO PIRATES",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Muthuvelu k",
    "email": "muthupro23@gmail.com",
    "phone": "9566583523",
    "college": "dhanalakshmi srinivasan engineering college (autonomous)",
    "members": "abinesh a, anwar a, balaji k",
    "utr": "664180144653",
    "isAdmin": false
  },
  {
    "id": 39,
    "regId": "CODIENYCH-2026-0039",
    "teamId": "CODIENYCH-2026-0039",
    "teamName": "Ai xora",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "Varshini.A",
    "email": "varshinialagesan911@gmail.com",
    "phone": "9944395465",
    "college": "Mahendra Engineering College",
    "members": "Poornima.M, Nirmalraj.K",
    "utr": "627403717423",
    "isAdmin": false
  },
  {
    "id": 40,
    "regId": "CODIENYCH-2026-0040",
    "teamId": "CODIENYCH-2026-0040",
    "teamName": "TEAM S4",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "SAKTHIVEL. T",
    "email": "sakthi88705@gmail.com",
    "phone": "7708927905",
    "college": "Dhanalakshmi Srinivasan Engineering College (Autonomous), Perambalur",
    "members": "Shakeen.D, saranraj.d, tamizhselvan.u",
    "utr": "664177666103",
    "isAdmin": false
  },
  {
    "id": 41,
    "regId": "CODIENYCH-2026-0041",
    "teamId": "CODIENYCH-2026-0041",
    "teamName": "Zentra",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 3,
    "leader": "DHIVYASRI M",
    "email": "dhivyasri0126@gmail.com",
    "phone": "6383126118",
    "college": "DR.N.G.P. Institute of Technology",
    "members": "ABINAYA G, ADHITHYAN K V",
    "utr": "130331446287",
    "isAdmin": false
  },
  {
    "id": 42,
    "regId": "CODIENYCH-2026-0042",
    "teamId": "CODIENYCH-2026-0042",
    "teamName": "AI_TECHNICIANS",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "LOGISARAN T",
    "email": "tlogisaran2005@gmail.com",
    "phone": "7010665856",
    "college": "NANDHA ENGINEERING COLLEGE",
    "members": "RAGUL V, THULASI MANIKANDAN S, YASHWAND S, SYED ABUBAKKAR SIDDHIQUE, ABHISHEK JS",
    "utr": "ragulragul4796@oksbi",
    "isAdmin": false
  },
  {
    "id": 43,
    "regId": "CODIENYCH-2026-0043",
    "teamId": "CODIENYCH-2026-0043",
    "teamName": "Kalvi Coders",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Elango .S",
    "email": "sivakumarelango10@gmail.com",
    "phone": "6379883404",
    "college": "Yenepoya University, bangalore",
    "members": "prajith p, karmjit S g, yashas k a",
    "utr": "664149969029",
    "isAdmin": false
  },
  {
    "id": 44,
    "regId": "CODIENYCH-2026-0044",
    "teamId": "CODIENYCH-2026-0044",
    "teamName": "Next Coders",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "A.N.Gerupakar",
    "email": "gerupakar68@gmail.com",
    "phone": "8610228152",
    "college": "yenepoya deemed to be university bengaluru",
    "members": "Aishwarya gowdaa, Kethan T, Meghana P Banda, RAYAPURAM VIKRAM, lakshan durai",
    "utr": "664171787394",
    "isAdmin": false
  },
  {
    "id": 45,
    "regId": "CODIENYCH-2026-0045",
    "teamId": "CODIENYCH-2026-0045",
    "teamName": "STARK-X",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "PRIYANKA G",
    "email": "priyanka.gisp@gmail.com",
    "phone": "+919345490169",
    "college": "K S Rangasamy College of technology",
    "members": "ANANtharajagopalan m, abinaya m, rithika g",
    "utr": "priyanka.gisp@okhdfcbank",
    "isAdmin": false
  },
  {
    "id": 46,
    "regId": "CODIENYCH-2026-0046",
    "teamId": "CODIENYCH-2026-0046",
    "teamName": "DEBUGGERS",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 3,
    "leader": "R. Devadharshini",
    "email": "rdevadharshini455@gmail.com",
    "phone": "8667750073",
    "college": "IFET college of engineering",
    "members": "aravind.i, suthakar.p",
    "utr": "877919508165",
    "isAdmin": false
  },
  {
    "id": 47,
    "regId": "CODIENYCH-2026-0047",
    "teamId": "CODIENYCH-2026-0047",
    "teamName": "Blast",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Kanishkaa B M",
    "email": "717824p323@kce.ac.in",
    "phone": "6385592646",
    "college": "Karpagam college of engineering",
    "members": "SAKTHISWAR b, Nithya sree s, Mathan b",
    "utr": "627588104721",
    "isAdmin": false
  },
  {
    "id": 48,
    "regId": "CODIENYCH-2026-0048",
    "teamId": "CODIENYCH-2026-0048",
    "teamName": "Byte force",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "kowshik E",
    "email": "kka099285@gmail.com",
    "phone": "9345261084",
    "college": "Excel Engineering College",
    "members": "Gopinathan r, Gowtham k, Siva r, TAMILMUTHAN S",
    "utr": "627563909462",
    "isAdmin": false
  },
  {
    "id": 49,
    "regId": "CODIENYCH-2026-0049",
    "teamId": "CODIENYCH-2026-0049",
    "teamName": "Byte Us",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Renuka . u",
    "email": "renuka.umasankar@gmail.com",
    "phone": "9342959532",
    "college": "velalar college of engineering and technology",
    "members": "sumithradevi.t, samiksha.s, sahana.t, yuvaraj.s.k, rohith thatchana moorthi.n",
    "utr": "samiselvam8028@okhdfcbank",
    "isAdmin": false
  },
  {
    "id": 50,
    "regId": "CODIENYCH-2026-0050",
    "teamId": "CODIENYCH-2026-0050",
    "teamName": "Genz_AI",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 5,
    "leader": "HARINARAYANAN S",
    "email": "harinarayanan2108@gmail.com",
    "phone": "6379263528",
    "college": "DHANALAKSHMI SRINIVASAN ENGINEERING COLLEGE",
    "members": "bhuvanesh v, gokul m, AHIL M, GOWTHAM S",
    "utr": "130611835133",
    "isAdmin": false
  },
  {
    "id": 51,
    "regId": "CODIENYCH-2026-0051",
    "teamId": "CODIENYCH-2026-0051",
    "teamName": "One_Piece",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "Naveen Kumar R",
    "email": "nknavi3107@gmail.com",
    "phone": "9843972234",
    "college": "Nandha engineering college",
    "members": "Madhubalan S, Shailesh K M, Sasankanth m",
    "utr": "627639518415",
    "isAdmin": false
  },
  {
    "id": 52,
    "regId": "CODIENYCH-2026-0052",
    "teamId": "CODIENYCH-2026-0052",
    "teamName": "Nithya priya",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "Nithya priya ST",
    "email": "nithyapriyanithya4@gmail.com",
    "phone": "8778483357",
    "college": "Mahendra Engineering college",
    "members": "Punithasri, Praba",
    "utr": "thennarasu2892007@oksbi",
    "isAdmin": false
  },
  {
    "id": 53,
    "regId": "CODIENYCH-2026-0053",
    "teamId": "CODIENYCH-2026-0053",
    "teamName": "HEX_CORPS",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "Harisaran R",
    "email": "harisaransboa9b@gmail.com",
    "phone": "+91 8248625381",
    "college": "Dhanalakshmi srinivasan university",
    "members": "Jairaman s, harini anudhu m, priyadharshini V R",
    "utr": "615242653279",
    "isAdmin": false
  },
  {
    "id": 54,
    "regId": "CODIENYCH-2026-0054",
    "teamId": "CODIENYCH-2026-0054",
    "teamName": "HOUSE TARGARYEN",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "AATHI SIVANESH K",
    "email": "joegoldberg1801@gmail.com",
    "phone": "7373344720",
    "college": "SHREE VENKATESHWARA HI-TECH ENGINEERING COLLEGE",
    "members": "RISHU KUMAR M, AKILESH G, DINESH MURUGAN A, ELANCHEZHIAN V, BENJAMIN C",
    "utr": "6276380753",
    "isAdmin": false
  },
  {
    "id": 55,
    "regId": "CODIENYCH-2026-0055",
    "teamId": "CODIENYCH-2026-0055",
    "teamName": "Tetracore",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "GAYATHRI S",
    "email": "gayathrisudhasharavanan@gmail.com",
    "phone": "9677722643",
    "college": "Vellalar college of engineering and technology",
    "members": "Deepak K, Mythreyee UT, Gowtham P",
    "utr": "EZE0222899@CUB",
    "isAdmin": false
  },
  {
    "id": 56,
    "regId": "CODIENYCH-2026-0056",
    "teamId": "CODIENYCH-2026-0056",
    "teamName": "HIKE RAIDERS",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Hari Karan",
    "email": "itz753781@gmail.com",
    "phone": "+919080549176",
    "college": "IFET COLLEGE OF ENGINEERING VILLUPURAM",
    "members": "MOHANRAJ S, PRATHEESH G, Hariprasadh S",
    "utr": "itz753781-1@oksbi",
    "isAdmin": false
  },
  {
    "id": 57,
    "regId": "CODIENYCH-2026-0057",
    "teamId": "CODIENYCH-2026-0057",
    "teamName": "Mission Pirates",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 3,
    "leader": "Kirthick Soma Sundaram G",
    "email": "hirthicksomasundaram.27@gmail.com",
    "phone": "9043852791",
    "college": "NPR College of Engineering and Technology",
    "members": "Santhosh Babiyan C, Prasanna Venkatesh P",
    "utr": "130644462988",
    "isAdmin": false
  },
  {
    "id": 58,
    "regId": "CODIENYCH-2026-0058",
    "teamId": "CODIENYCH-2026-0058",
    "teamName": "BIONEX",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "RishiKesh.S",
    "email": "rishikesh051207@gmail.com",
    "phone": "8148245334",
    "college": "PGP COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "members": "SATHYA.T, THAMARAISELVAN, BALASUBRAMANI.S",
    "utr": "627610745589",
    "isAdmin": false
  },
  {
    "id": 59,
    "regId": "CODIENYCH-2026-0059",
    "teamId": "CODIENYCH-2026-0059",
    "teamName": "Captain pirates",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "Thamil Selvan.k",
    "email": "thamilselvank69@gmail.com",
    "phone": "9042960137",
    "college": "Kangeyam institute of technology",
    "members": "K.swathika, NIRMAL S, SRI KARTHIKA P",
    "utr": "427161014161",
    "isAdmin": false
  },
  {
    "id": 60,
    "regId": "CODIENYCH-2026-0060",
    "teamId": "CODIENYCH-2026-0060",
    "teamName": "DREAM_CHAMBERS",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "VASUNDRAM",
    "email": "vasundramohanraj2007@gmail.com",
    "phone": "6385590517",
    "college": "PSNA COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "members": "SUBHASRI S, sathish kumar s, SHABANA BANU S",
    "utr": "130658771171",
    "isAdmin": false
  },
  {
    "id": 61,
    "regId": "CODIENYCH-2026-0061",
    "teamId": "CODIENYCH-2026-0061",
    "teamName": "Undefined",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Jaisha J A",
    "email": "jaishajeyasingh@gmail.com",
    "phone": "7395 980 773",
    "college": "easwari engineering college",
    "members": "Harini M, Harini Prakash, Jaya Viknesh s g, Krishnan S, Kishore V",
    "utr": "664277809346",
    "isAdmin": false
  },
  {
    "id": 62,
    "regId": "CODIENYCH-2026-0062",
    "teamId": "CODIENYCH-2026-0062",
    "teamName": "Infinite loop",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Sugandakumar V",
    "email": "sugandakumar001@gmail.com",
    "phone": "6369333713",
    "college": "Velalar college of engineering and technology",
    "members": "Vandhana B, Shreya, Manikandan V",
    "utr": "627614889973",
    "isAdmin": false
  },
  {
    "id": 63,
    "regId": "CODIENYCH-2026-0063",
    "teamId": "CODIENYCH-2026-0063",
    "teamName": "Phoenix",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Phoenix",
    "email": "prasatharumugam575@gmail.com",
    "phone": "9952219264",
    "college": "Nandha engineering college",
    "members": "Santhana bharathi m, Menaka muthukuram, Pooja M.V, Bharath G, Ajay a",
    "utr": "664285712527",
    "isAdmin": false
  },
  {
    "id": 64,
    "regId": "CODIENYCH-2026-0064",
    "teamId": "CODIENYCH-2026-0064",
    "teamName": "Titan",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Mugilarasuk",
    "email": "kmugil738@gmail.com",
    "phone": "9629110809",
    "college": "Shree Venkateshwara hi-tech engineering college",
    "members": "Naveenkumar s, Balaselvam m, Prabhakaran R",
    "utr": "664295003624",
    "isAdmin": false
  },
  {
    "id": 65,
    "regId": "CODIENYCH-2026-0065",
    "teamId": "CODIENYCH-2026-0065",
    "teamName": "InnovateX",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 3,
    "leader": "Mathavan M",
    "email": "mathavantn07@gmail.com",
    "phone": "7397265541",
    "college": "NPR COLLEGE OF ENGINEERING AND TECHNOLOGY",
    "members": "Manoj Kumar S, Silambarasan S",
    "utr": "130667829589",
    "isAdmin": false
  },
  {
    "id": 66,
    "regId": "CODIENYCH-2026-0066",
    "teamId": "CODIENYCH-2026-0066",
    "teamName": "Dead Men Tell No Tales",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 3,
    "leader": "Yokeshwar Balasubramani",
    "email": "yokeshff@gmail.com",
    "phone": "+917904455939",
    "college": "Psnacet",
    "members": "Vishak adharsh, Tharanidharan",
    "utr": "627642301778",
    "isAdmin": false
  },
  {
    "id": 67,
    "regId": "CODIENYCH-2026-0067",
    "teamId": "CODIENYCH-2026-0067",
    "teamName": "UNKNOWN ERROR",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 5,
    "leader": "PAVISH G",
    "email": "pavishg04@gmail.com",
    "phone": "8072860669",
    "college": "DR NGP INSTITUTE OF TECHNOLOGY",
    "members": "KISHORE N, jenifer m, madhu prabha p, dharunesh b",
    "utr": "664273518375",
    "isAdmin": false
  },
  {
    "id": 68,
    "regId": "CODIENYCH-2026-0068",
    "teamId": "CODIENYCH-2026-0068",
    "teamName": "404_Founders",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Subhaharini sri.kv",
    "email": "harinivenkatesh659@gmail.com",
    "phone": "8838692869",
    "college": "Shree Venkateswara Hi-tech engineering College",
    "members": "hema priya.s, Jerin mofi.j, Megavarshini.g, Preethi.r, Dharani.r",
    "utr": "664259525463",
    "isAdmin": false
  },
  {
    "id": 69,
    "regId": "CODIENYCH-2026-0069",
    "teamId": "CODIENYCH-2026-0069",
    "teamName": "RUDRANETRA",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 6,
    "leader": "AKASH A R",
    "email": "26csl03@kpriet.ac.in",
    "phone": "9025966646",
    "college": "KPR INSTITUTE of engineering and technology",
    "members": "Aakash r, Debangi mondal, Roshni kailash brindha, Rithik saran s, Kanishka u",
    "utr": "130675610651",
    "isAdmin": false
  },
  {
    "id": 70,
    "regId": "CODIENYCH-2026-0070",
    "teamId": "CODIENYCH-2026-0070",
    "teamName": "Spark_X_AI",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "Harish p",
    "email": "harishpalani577@gmail.com",
    "phone": "6369471255",
    "college": "Er.Perumal Manimekalai College of Engineering - Hosur",
    "members": "Mukesh Y, Lithik Raj B.G, Kaviyarasu K, Poovendiran V, Ganesh Kaarthi S",
    "utr": "664265961429",
    "isAdmin": false
  },
  {
    "id": 71,
    "regId": "CODIENYCH-2026-0071",
    "teamId": "CODIENYCH-2026-0071",
    "teamName": "Aquanova",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Kavya V",
    "email": "kavyaparvathy61@gmail.com",
    "phone": "8754724375",
    "college": "KPRIET",
    "members": "Santhiya S, Dharani r, Bhavani shree r",
    "utr": "664289620600",
    "isAdmin": false
  },
  {
    "id": 72,
    "regId": "CODIENYCH-2026-0072",
    "teamId": "CODIENYCH-2026-0072",
    "teamName": "Alpha tetron",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "Jeevitha V",
    "email": "25am042@kpriet.ac.in",
    "phone": "7812847286",
    "college": "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "members": "Kaniksha S, Kishore BN, Krithik kb",
    "utr": "627751697719",
    "isAdmin": false
  },
  {
    "id": 73,
    "regId": "CODIENYCH-2026-0073",
    "teamId": "CODIENYCH-2026-0073",
    "teamName": "Term warriors",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Dhinakar S",
    "email": "dhinakard047@gmail.com",
    "phone": "8056590373",
    "college": "Shree Venkateshwara hi-tech engineering college",
    "members": "Dhineskumar M, Karthik M V, Mukesh S, Nagaboopathi K, Sukumaran K",
    "utr": "664320936948",
    "isAdmin": false
  },
  {
    "id": 74,
    "regId": "CODIENYCH-2026-0074",
    "teamId": "CODIENYCH-2026-0074",
    "teamName": "Team Nexora",
    "originalTrack": "Cyber Security",
    "domain": "Cybersecurity & Privacy",
    "size": 5,
    "leader": "Suba sri.b",
    "email": "subasrib82@gmail.com",
    "phone": "8610914228",
    "college": "Nandha Engineering college",
    "members": "Supriya.k, Dharshini AM, Sharmila.p, Vedhasree.p",
    "utr": "130686068124",
    "isAdmin": false
  },
  {
    "id": 75,
    "regId": "CODIENYCH-2026-0075",
    "teamId": "CODIENYCH-2026-0075",
    "teamName": "Tech_fluxz",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 6,
    "leader": "JANANI R",
    "email": "janani2392007@gmail.com",
    "phone": "+919500933225",
    "college": "Shree venkateshwara hi-tech engineering college",
    "members": "Harini.J, Olirmathi.s.p, Thavamani.S, Thanishka.N, Sudalai laskhmi",
    "utr": "664316951919",
    "isAdmin": false
  },
  {
    "id": 76,
    "regId": "CODIENYCH-2026-0076",
    "teamId": "CODIENYCH-2026-0076",
    "teamName": "SIGMA",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "NAVEEN",
    "email": "naveenarikrishnan2510@gmail.com",
    "phone": "6383952836",
    "college": "Kangeyam Institute of technology",
    "members": "Yogeshwaran, Benasir Nisha S, Mohamed Farook S, Deepsika s, Vivek hari Narayanan",
    "utr": "627764277408",
    "isAdmin": false
  },
  {
    "id": 77,
    "regId": "CODIENYCH-2026-0077",
    "teamId": "CODIENYCH-2026-0077",
    "teamName": "Innovexa",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "KANIKA C",
    "email": "kanikachandrasekar@gmail.com",
    "phone": "+91 86800 47376",
    "college": "Dr.N.G.P. INSTITUTE OF TECHNOLOGY",
    "members": "Nandhini S, NAMRITHA G",
    "utr": "T2610041134164195516455",
    "isAdmin": false
  },
  {
    "id": 78,
    "regId": "CODIENYCH-2026-0078",
    "teamId": "CODIENYCH-2026-0078",
    "teamName": "Invincible",
    "originalTrack": "Cyber Security",
    "domain": "Cybersecurity & Privacy",
    "size": 5,
    "leader": "LOGANAYAKI R",
    "email": "loganayakiramesh91@gmil.com",
    "phone": "8015622656",
    "college": "shree Venkateshwara hi tec engineering college",
    "members": "DHAVA SRI .V, POORVIKA, MONISHA V, LALITHAMBIKA",
    "utr": "710814424886",
    "isAdmin": false
  },
  {
    "id": 79,
    "regId": "CODIENYCH-2026-0079",
    "teamId": "CODIENYCH-2026-0079",
    "teamName": "CODE.X",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "NIRANJANA B",
    "email": "kavinira2008@gmail.com",
    "phone": "7806819234",
    "college": "Shree vengadeshwara hi -tech engineering college",
    "members": "Vasanth p k, Ayyappan s j, Akash t",
    "utr": "664332847251",
    "isAdmin": false
  },
  {
    "id": 80,
    "regId": "CODIENYCH-2026-0080",
    "teamId": "CODIENYCH-2026-0080",
    "teamName": "DigitalCorsairs",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Sathya Swetha P",
    "email": "24uem024@avinuty.ac.in",
    "phone": "9384221210",
    "college": "Avinashilingam Institute for Home Science and Higher Education for Women",
    "members": "Sri Saranya N, Yoshitha S, Naveetha Shri S",
    "utr": "664300886633",
    "isAdmin": false
  },
  {
    "id": 81,
    "regId": "CODIENYCH-2026-0081",
    "teamId": "CODIENYCH-2026-0081",
    "teamName": "Demon circuit",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 3,
    "leader": "Sriram",
    "email": "sriram7358ram@gmail.com",
    "phone": "7305862596",
    "college": "Mahendra engineering college",
    "members": "Sivasujith, Thavaseelan",
    "utr": "664370376118",
    "isAdmin": false
  },
  {
    "id": 82,
    "regId": "CODIENYCH-2026-0082",
    "teamId": "CODIENYCH-2026-0082",
    "teamName": "CODER.X",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "Logesh V",
    "email": "logeshv6116@gmail.com",
    "phone": "9342758607",
    "college": "Excel engineering college",
    "members": "Hirankumar G, Manikandan kk, Kirubakaran K, Kishore s",
    "utr": "T2610041738464957532724",
    "isAdmin": false
  },
  {
    "id": 83,
    "regId": "CODIENYCH-2026-0083",
    "teamId": "CODIENYCH-2026-0083",
    "teamName": "Vision NextAi",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Nanthish S",
    "email": "nanthishvaran17@gmail.com",
    "phone": "9042020879",
    "college": "NANDHA ENGINEERING COLLEGE",
    "members": "Kavin b, Pradeepa M, Mahilnethra SK, Rohith R, Jeevitha S",
    "utr": "664327678258",
    "isAdmin": false
  },
  {
    "id": 84,
    "regId": "CODIENYCH-2026-0084",
    "teamId": "CODIENYCH-2026-0084",
    "teamName": "TECHFUSION",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Nitish D",
    "email": "dnitish2006@gmail.com",
    "phone": "8368172169",
    "college": "kpr institute of engineering and technology",
    "members": "dhananjai P, ABhinav aadhitya ss, dharan kumar b",
    "utr": "005568584022",
    "isAdmin": false
  },
  {
    "id": 85,
    "regId": "CODIENYCH-2026-0085",
    "teamId": "CODIENYCH-2026-0085",
    "teamName": "ODD Byte",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "Lathika Saran R",
    "email": "lathikasaran26@gmail.com",
    "phone": "7904204169",
    "college": "Thiagrajar college of engineering",
    "members": "SRIJHA K, Maanashvini R V, Kirithik M",
    "utr": "615348450472",
    "isAdmin": false
  },
  {
    "id": 86,
    "regId": "CODIENYCH-2026-0086",
    "teamId": "CODIENYCH-2026-0086",
    "teamName": "POLYFORK",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "GANTHA SWAROOPAN V M",
    "email": "25am025@kpriet.ac.in",
    "phone": "7639512192",
    "college": "KPR INSTITUTE OF ENGINEERING AND TECHNOLOGY",
    "members": "HANITHA R, Jayashree b",
    "utr": "130718164469",
    "isAdmin": false
  },
  {
    "id": 87,
    "regId": "CODIENYCH-2026-0087",
    "teamId": "CODIENYCH-2026-0087",
    "teamName": "TEAM HITLER",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "GOKUL EASWAR R",
    "email": "eswargokul229@gmail.com",
    "phone": "7094531307",
    "college": "Shree venkateshwara hi-tech engineering college",
    "members": "Navanithan s, Arun kumar G, Janarthan m",
    "utr": "0055722865571",
    "isAdmin": false
  },
  {
    "id": 88,
    "regId": "CODIENYCH-2026-0088",
    "teamId": "CODIENYCH-2026-0088",
    "teamName": "Zentrix",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "Abinaya S",
    "email": "abinaya2966@gmail.com",
    "phone": "8667651270",
    "college": "Sns college of technology",
    "members": "Srilekha R, Harshada R, Abinaya K, Dhanusha D",
    "utr": "627794438990",
    "isAdmin": false
  },
  {
    "id": 89,
    "regId": "CODIENYCH-2026-0089",
    "teamId": "CODIENYCH-2026-0089",
    "teamName": "Nano Brains",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 3,
    "leader": "Dhanush S.T.",
    "email": "dhanushdhanushst@gmail.com",
    "phone": "7356654999",
    "college": "NANDHA ENGINEERING COLLEGE",
    "members": "Kishor S, Gayatri B",
    "utr": "627794304094",
    "isAdmin": false
  },
  {
    "id": 90,
    "regId": "CODIENYCH-2026-0090",
    "teamId": "CODIENYCH-2026-0090",
    "teamName": "Pixel mind",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "Sarithra S",
    "email": "sarithra9787@gmail.com",
    "phone": "9787106124",
    "college": "Mahendra institute of technology",
    "members": "Elamathi S, Madhumita M, Birundha k, Naveena r, KAMALI S P",
    "utr": "Senthil76392@okicici",
    "isAdmin": false
  },
  {
    "id": 91,
    "regId": "CODIENYCH-2026-0091",
    "teamId": "CODIENYCH-2026-0091",
    "teamName": "PIXEL PERFECTS",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "NISHANTH M M",
    "email": "24am033@kpriet.ac.in",
    "phone": "9843969790",
    "college": "KPR Institute of Engineering and Technology",
    "members": "NARENDHIRAN k, jeswanthkavi a, sana farhana j, rashmi s",
    "utr": "627787612242",
    "isAdmin": false
  },
  {
    "id": 92,
    "regId": "CODIENYCH-2026-0092",
    "teamId": "CODIENYCH-2026-0092",
    "teamName": "The Horizon Chasers",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 4,
    "leader": "AKASH T",
    "email": "25am007@kpriet.ac.in",
    "phone": "+91 9600547957",
    "college": "KPRIET",
    "members": "JAI SHREE P B, ARAVIND S, ASHWANTH N",
    "utr": "954769623494",
    "isAdmin": false
  },
  {
    "id": 93,
    "regId": "CODIENYCH-2026-0093",
    "teamId": "CODIENYCH-2026-0093",
    "teamName": "Solvix",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 3,
    "leader": "Praveen R",
    "email": "rpraveenravi06@gmail.com",
    "phone": "9361879638",
    "college": "Dr n g p institute of technology",
    "members": "kishore s, naresh k",
    "utr": "201555135845",
    "isAdmin": false
  },
  {
    "id": 94,
    "regId": "CODIENYCH-2026-0094",
    "teamId": "CODIENYCH-2026-0094",
    "teamName": "Pixel Pirates",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "SASIKIRAN S",
    "email": "sasikiranbecse@gmail.com",
    "phone": "+19 7904708503",
    "college": "MAHENDRA ENGINEERING COLLEGE",
    "members": "VISHNUKANDH S, RAVIVARMA S, RANJITH G",
    "utr": "627701315226",
    "isAdmin": false
  },
  {
    "id": 95,
    "regId": "CODIENYCH-2026-0095",
    "teamId": "CODIENYCH-2026-0095",
    "teamName": "ZEIGEN",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 6,
    "leader": "SRAVANKUMAR G",
    "email": "sravan30112006@gmail.com",
    "phone": "6381846548",
    "college": "K.L.N. COLLEGE OF ENGINEERING",
    "members": "VISHVANATHAN M, RAMACHANDRAN P, SIVA SAKTHI SANTHOSH K, VENKATESWARAN P K, SANTHOSHKUMAR S",
    "utr": "627702989234",
    "isAdmin": false
  },
  {
    "id": 96,
    "regId": "CODIENYCH-2026-0096",
    "teamId": "CODIENYCH-2026-0096",
    "teamName": "AS HACKERS",
    "originalTrack": "AI & Machine Learning (AI ML)",
    "domain": "Artificial Intelligence & ML",
    "size": 3,
    "leader": "Sajai S",
    "email": "jayanthilohita@gmail.com",
    "phone": "+91 9600322412",
    "college": "SNS College of Technology",
    "members": "ANDIAPPAN K, Dharshan s",
    "utr": "251714940734",
    "isAdmin": false
  },
  {
    "id": 97,
    "regId": "CODIENYCH-2026-0097",
    "teamId": "CODIENYCH-2026-0097",
    "teamName": "MINDMESH",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Gajavalli S",
    "email": "gaja262007@gmail.com",
    "phone": "9384800801",
    "college": "KSR COLLEGE OF ENGINEERING",
    "members": "Dhanushni R, Gowtham B, Bathrinath M",
    "utr": "627705125643",
    "isAdmin": false
  },
  {
    "id": 98,
    "regId": "CODIENYCH-2026-0098",
    "teamId": "CODIENYCH-2026-0098",
    "teamName": "Code vortex",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 4,
    "leader": "Deepika Kulandaivelu",
    "email": "deepikakulandai2007@gmail.com",
    "phone": "8838091920",
    "college": "KSR college of Engineering",
    "members": "Aysha jasmine A, Gowtham R, Deepan M",
    "utr": "627705707123",
    "isAdmin": false
  },
  {
    "id": 99,
    "regId": "CODIENYCH-2026-0099",
    "teamId": "CODIENYCH-2026-0099",
    "teamName": "SINCET AI BOYS",
    "originalTrack": "Web & App Development",
    "domain": "Web & Mobile Development",
    "size": 5,
    "leader": "V.Mahir Mohamed",
    "email": "mahirmohamedsrm@gmail.com",
    "phone": "6381711262",
    "college": "Sir Issac Newton college of engineering and technology",
    "members": "M.Gokul, S.Sanjai, M.MuthuKrishnan, J.Maideen jafrith",
    "utr": "T2610042219026658368719",
    "isAdmin": false
  },
  {
    "id": 100,
    "regId": "CODIENYCH-2026-0100",
    "teamId": "CODIENYCH-2026-0100",
    "teamName": "UNO WARRIORS",
    "originalTrack": "Internet of Things (IOT)",
    "domain": "Internet of Things (IoT)",
    "size": 4,
    "leader": "ABDUL ANEEF U",
    "email": "abdulanif777@gmail.com",
    "phone": "9080790278",
    "college": "Excel Engineering College",
    "members": "RAGUL R, JEEVA SARATH M, Jeevanandam S",
    "utr": "627704307925",
    "isAdmin": false
  },
  {
    "id": 101,
    "regId": "CODIENYCH-ADMIN",
    "teamId": "CODIENYCH-ADMIN",
    "teamName": "Admin Team",
    "originalTrack": "All Domains",
    "domain": "Artificial Intelligence & ML",
    "size": 1,
    "leader": "Event Administrator",
    "email": "admin@codienych.org",
    "phone": "0000000000",
    "college": "CODIENYCH Organizing Committee",
    "members": "Event Admin Master",
    "utr": "ADMIN-TX-0000",
    "isAdmin": true
  }
];
